discarding /usr/local/anaconda/anaconda2/bin from PATH
prepending /users/PCON0003/osu10670/.conda/envs/galsim/bin to PATH
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
WARNING: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)" [astropy._erfa.core]
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
        sim.pointing.update_sca(sca)
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
        sim.pointing.update_sca(sca)
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
sim.pointing.update_sca(sca)
    sim.pointing.update_sca(sca)
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
    sim.pointing.update_sca(sca)
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
    sim.pointing.update_sca(sca)
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
    sim.pointing.update_sca(sca)
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
    sim.pointing.update_sca(sca)
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
sim.pointing.update_sca(sca)
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
        sim.pointing.update_sca(sca)
    self.get_psf() # Get the new PSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
    self.get_psf() # Get the new PSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
    sim.pointing.update_sca(sca)
    sim.pointing.update_sca(sca)
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
self.get_psf() # Get the new PSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
    sim.pointing.update_sca(sca)
    sim.pointing.update_sca(sca)
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
    sim.pointing.update_sca(sca)
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
    self.get_psf() # Get the new PSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
    sim.pointing.update_sca(sca)
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
    self.get_psf() # Get the new PSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
    self.get_psf() # Get the new PSF
    self.get_psf() # Get the new PSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
    self.get_psf() # Get the new PSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
    self.get_psf() # Get the new PSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
    high_accuracy       = high_accuracy,
    self.get_psf() # Get the new PSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
    high_accuracy       = high_accuracy,
    sim.pointing.update_sca(sca)
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
    self.get_psf() # Get the new PSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
    self.get_psf() # Get the new PSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
    self.get_psf() # Get the new PSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
    high_accuracy       = high_accuracy,
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
    self.get_psf() # Get the new PSF
    self.get_psf() # Get the new PSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
    self.get_psf() # Get the new PSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
    high_accuracy       = high_accuracy,
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
    high_accuracy       = high_accuracy,
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
    high_accuracy       = high_accuracy,
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
    high_accuracy       = high_accuracy,
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
    high_accuracy       = high_accuracy,
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
    high_accuracy       = high_accuracy,
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
    high_accuracy       = high_accuracy,
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
    self.get_psf() # Get the new PSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
    high_accuracy       = high_accuracy,
    high_accuracy       = high_accuracy,
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
    high_accuracy       = high_accuracy,
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
    sim.pointing.update_sca(sca)
Traceback (most recent call last):
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 3078, in <module>
    high_accuracy       = high_accuracy,
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
    high_accuracy       = high_accuracy,
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
    high_accuracy       = high_accuracy,
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
    high_accuracy       = high_accuracy,
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
    self.get_psf() # Get the new PSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
    sim.pointing.update_sca(sca)
    high_accuracy       = high_accuracy,
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
    sim.pointing.update_sca(sca)
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
    use_aberrations += extra_aberrations
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
    use_aberrations += extra_aberrations
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
    use_aberrations += extra_aberrations
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
    use_aberrations += extra_aberrations
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
    use_aberrations += extra_aberrations
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
    use_aberrations += extra_aberrations
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 454, in update_sca
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
    self.get_psf() # Get the new PSF
        use_aberrations += extra_aberrations
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
    use_aberrations += extra_aberrations
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
use_aberrations += extra_aberrations
    use_aberrations += extra_aberrations
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
    use_aberrations += extra_aberrations
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
    use_aberrations += extra_aberrations
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
    use_aberrations += extra_aberrations
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
    use_aberrations += extra_aberrations
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
    use_aberrations += extra_aberrations
    self.get_psf() # Get the new PSF
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
    use_aberrations += extra_aberrations
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
  File "../../wfirst_imsim/wfirst_imsim/simulate.py", line 483, in get_psf
    use_aberrations += extra_aberrations
    high_accuracy       = high_accuracy,
    use_aberrations += extra_aberrations
    high_accuracy       = high_accuracy,
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 229, in getPSF
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
    high_accuracy[i], pupil_plane_type[i], gsparams[i])
    use_aberrations += extra_aberrations
  File "/users/PCON0003/osu10670/.conda/envs/galsim/lib/python2.7/site-packages/galsim/wfirst/wfirst_psfs.py", line 281, in _get_single_PSF
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
    use_aberrations += extra_aberrations
ValueError: operands could not be broadcast together with shapes (23,) (12,) (23,) 
